### PR TITLE
Update my email

### PR DESCRIPTION
**Pull request by szokovacs**

### CODE REVIEW

**Comment by gnomesysadmins** [comment]
Thank you for contributing to five-or-more!

five-or-more uses GitLab for code review. As such we have forwarded
your contribution to the GNOME official GitLab instance:

https://gitlab.gnome.org/GNOME/five-or-more/-/issues/24

GNOME's GitLab instance also supports GitHub as one of the possible
authentication method in case you'd like to follow up on the above
issue. You can login at the following URL:

https://gitlab.gnome.org/users/sign_in

If you are interested in sticking around within the GNOME community we
encourage you to read the following documents:

https://www.gnome.org/get-involved
and
https://wiki.gnome.org/Newcomers

**Comment by evfool** [comment]
Hi @szokovacs. Could you please remove the .po files from this MR? They are purely translations, and will get regenerated automatically based on the existing files, so it is enough to update your email in the other places and it will get propagated. That way we also avoid purely translation-based merge conflicts.

**Comment by aklapper** [comment]
This patch needs to go into GNOME Gitlab instead

**Comment by evfool** [comment]
> This patch needs to go into GNOME Gitlab instead

It was automatically forwarded, I received the mail from GNOME gitlab, I just wanted to let the original author know that the MR should be updated without PO file changes here.

**Comment by aklapper** [comment]
I know. :) A ticket was forwarded; but not a Merge Request.

**Pull request closed without merging**
